#!/usr/bin/env python
import SimpleHTTPServer
import SocketServer

class MyRequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == '/':
            self.path = '/index.html'
        if (   self.path.endswith(".png") 
            or self.path.endswith(".js")
            or self.path.endswith(".jpg")
            or self.path.endswith(".html")
            or self.path.endswith(".css") ):
            pass
        else:
            if ( self.path.endswith("/") ):
                self.path += 'index.html'
            else:
                self.path += '.html'
        return SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)

Handler = MyRequestHandler
server = SocketServer.TCPServer(('0.0.0.0', 8080), Handler)

print "serving your site on http://localhost:8080 "
server.serve_forever()
